import React from 'react';
import { GaitMetrics, UserProfile } from '../types';
import { Button } from './Button';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell } from 'recharts';

interface ResultsViewProps {
  metrics: GaitMetrics;
  user: UserProfile;
  onReset: () => void;
}

const StatCard: React.FC<{ label: string; value: string | number; unit?: string; description?: string; badge?: string }> = ({ label, value, unit, description, badge }) => (
  <div className="bg-white p-5 rounded-xl border border-gray-100 shadow-sm hover:shadow-md transition-shadow relative overflow-hidden">
    <p className="text-sm font-medium text-gray-500 mb-1">{label}</p>
    <div className="flex items-baseline">
      <span className="text-2xl font-bold text-gray-900">{value}</span>
      {unit && <span className="ml-1 text-sm text-gray-500">{unit}</span>}
    </div>
    {description && <p className="text-xs text-gray-400 mt-2">{description}</p>}
    {badge && (
        <div className="absolute top-0 right-0 bg-emerald-50 text-emerald-600 text-[10px] font-bold px-2 py-1 rounded-bl-lg border-l border-b border-emerald-100">
            {badge}
        </div>
    )}
  </div>
);

export const ResultsView: React.FC<ResultsViewProps> = ({ metrics, user, onReset }) => {
  
  // Transform data for charts
  // Normal cadence range 90-130
  const chartData = [
    { name: 'Your Cadence', value: metrics.cadence },
    { name: 'Normal Min', value: 90 },
    { name: 'Normal Max', value: 120 },
  ];

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="flex justify-between items-center">
        <div>
           <h2 className="text-2xl font-bold text-gray-900">Analysis Results</h2>
           <p className="text-gray-500">Subject: {user.firstName} {user.lastName} ({user.age}, {user.gender})</p>
        </div>
        <Button onClick={onReset} variant="secondary">New Analysis</Button>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="md:col-span-2 space-y-6">
             <div className="bg-indigo-50 border border-indigo-100 p-6 rounded-xl">
                <h3 className="font-semibold text-indigo-900 mb-2">Clinical Summary</h3>
                <p className="text-indigo-800 leading-relaxed">{metrics.analysisSummary}</p>
                <div className="mt-4 flex items-center text-xs text-indigo-600/70 bg-indigo-100/50 p-2 rounded w-fit">
                    <span className="mr-2">✨</span> 
                    <span>Generated by Gemini 2.0 Flash Vision Model</span>
                </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
                <StatCard 
                    label="Cadence" 
                    value={metrics.cadence} 
                    unit="spm" 
                    description="Steps per minute"
                    badge="CV ACCURATE"
                />
                <StatCard 
                    label="Step Count" 
                    value={metrics.stepCount} 
                    badge="CV ACCURATE"
                />
                <StatCard 
                    label="Mean Interval" 
                    value={metrics.meanStepInterval.toFixed(2)} 
                    unit="s" 
                    badge="CV CALCULATED"
                />
                <StatCard 
                    label="Step Time Var." 
                    value={metrics.stepTimeVariability} 
                    unit="ms" 
                    description="Consistency of steps"
                    badge="CV CALCULATED"
                />
            </div>
        </div>

        <div className="space-y-4">
             {/* Tracked Subject Verification Image */}
             {metrics.trackedSubjectImage && (
                <div className="bg-white p-4 rounded-xl border border-gray-200 shadow-sm">
                   <h3 className="text-sm font-semibold text-gray-900 mb-2 flex items-center">
                       <span className="w-2 h-2 bg-green-500 rounded-full mr-2"></span>
                       Analyzed Subject
                   </h3>
                   <div className="rounded-lg overflow-hidden border border-gray-100 relative bg-black aspect-video">
                       <img src={metrics.trackedSubjectImage} alt="Tracked Subject" className="w-full h-full object-contain" />
                       <div className="absolute bottom-0 left-0 right-0 bg-black/60 text-white text-[10px] p-1 text-center">
                           Skeletal tracking verification
                       </div>
                   </div>
                   <p className="text-xs text-gray-500 mt-2">
                       This image confirms which person was tracked during the analysis.
                   </p>
                </div>
             )}
            
             <div className="grid grid-cols-1 gap-4">
                <StatCard 
                    label="Gait Speed" 
                    value={metrics.gaitSpeed} 
                    description="Relative to normal"
                />
                <StatCard 
                    label="Base of Support" 
                    value={metrics.averageBaseOfSupportCm || metrics.baseOfSupport} 
                    unit={metrics.averageBaseOfSupportCm ? "cm" : ""}
                    badge={metrics.averageBaseOfSupportCm ? "CV CALCULATED" : "AI ESTIMATE"}
                />
             </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
         {/* Metric Visualization */}
        <div className="bg-white p-6 rounded-xl border border-gray-100 shadow-sm h-80">
            <h3 className="text-sm font-medium text-gray-500 mb-4">Cadence Comparison</h3>
            <ResponsiveContainer width="100%" height="100%">
                <BarChart data={chartData} margin={{ top: 20, right: 30, left: 20, bottom: 5 }}>
                <XAxis dataKey="name" tick={{fontSize: 12}} />
                <YAxis />
                <Tooltip cursor={{fill: '#f3f4f6'}} />
                <Bar dataKey="value" radius={[4, 4, 0, 0]}>
                    {chartData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={index === 0 ? '#4f46e5' : '#e2e8f0'} />
                    ))}
                </Bar>
                </BarChart>
            </ResponsiveContainer>
        </div>

        <div className="bg-slate-50 p-6 rounded-xl border border-slate-200 text-sm text-slate-600">
             <h3 className="font-semibold text-slate-800 mb-3">Analysis Methodology</h3>
             <ul className="space-y-3 list-disc list-inside">
                 <li>
                     <span className="font-medium text-slate-900">Step Detection:</span> Using MediaPipe Pose to track Euclidean distance between ankle joints (IDs 27 & 28).
                 </li>
                 <li>
                     <span className="font-medium text-slate-900">Base of Support:</span> Calculated as average heel width (cm) during double support phase, scaled by user height.
                 </li>
                 <li>
                     <span className="font-medium text-slate-900">Subject Verification:</span> The image on the right shows the skeletal tracking overlay to confirm the analyzed subject.
                 </li>
             </ul>
        </div>
      </div>
      
      <div className="text-center text-xs text-gray-400 mt-8 pb-8">
        Hybrid Analysis: Computer Vision (Quantitative) + Generative AI (Qualitative).
      </div>
    </div>
  );
};